FROM ubuntu:22.04

WORKDIR /usr/local/webserver/cmd/

ENV PORTFOLIOSERVER_PORT=""
ENV PORTFOLIOSERVER_DBIP=""
ENV PORTFOLIOSERVER_DBPORT=0
ENV PORTFOLIOSERVER_DBNAME=""
ENV PORTFOLIOSERVER_DBUSER=""
ENV PORTFOLIOSERVER_DBPASS=""
ENV PORTFOLIOSERVER_CERT=""
ENV PORTFOLIOSERVER_KEY=""

COPY build ../

EXPOSE 8080

CMD ["./server"]