FROM ubuntu:22.04

WORKDIR /usr/local/webserver/cmd/

ENV PORTFOLIOSERVER_PORT=8080
ENV PORTFOLIOSERVER_DBIP=127.0.0.1
ENV PORTFOLIOSERVER_DBPORT=5432
ENV PORTFOLIOSERVER_DBNAME=portfoliodb
ENV PORTFOLIOSERVER_DBUSER=test
ENV PORTFOLIOSERVER_DBPASS=test
ENV PORTFOLIOSERVER_CERT=../tls/cert.pem
ENV PORTFOLIOSERVER_KEY=../tls/key.pem

COPY build ../

EXPOSE 8080

CMD ["./server"]